### ISSUE TITLE
`insights.chrome.isProd` is false on https://prod.foo.redhat.com:1337/

### ISSUE THREAD

**Issue by josejulio** [RedHatInsights/insights-chrome#1124]
I was trying to test how something would look on prod (I have a conditional for `isProd`) and attempted to try on https://prod.foo.redhat.com:1337/

On the console I can see the following: 
```
> insights.chrome.isProd
false
```

Is this a bug or is expected behavior?

**Comment by Hyperkid123** [comment]
@josejulio Currently the `isProd` flag is set to true if the host is 'cloud.redhat.com'. Given that we have "prod" development env it would make sense to include it in the is Prod flag. @ryelo @karelhala what do you think?

**Comment by ryelo** [comment]
I'm not opposed to having it. However, I do think that `isProd` is technically doing its job here. 

We also have [a `getEnv()` flag](https://github.com/RedHatInsights/insights-chrome/blob/5533bd585c6b1e0fea61fe596207727816cb39ae/src/js/chrome/entry.js#L115) which is a little bit smarter because it's based on the [default routes](https://github.com/RedHatInsights/insights-chrome/blob/0c210033fb1eab4e9e5b7b4fd87f2e267e65d03a/src/js/jwt/constants.js#L2)

**Comment by karelhala** [comment]
@ryelo good point on the `getEnvironment` function. I think @josejulio is refering to this because of permissions to hide some UI parts, right? If that's the case, we could morphe this issue to add new permissions function `isEnvironment` and actually test if user is on qa, ci or prod env. Much better, than adding another if to the `isProd` check, which IMO should indicate that the user is on actual production environment, not on local prod one.

**Comment by Hyperkid123** [comment]
I think it's a bit confusing. If didn't know anything about our envs, I would also assume that `isProd` would be true on `prod.xxx.

I agree the is `isEnvironment` can actually mirror the URL partial.

**Comment by josejulio** [comment]
> I think @josejulio is refering to this because of permissions to hide some UI parts, right?

right

> which IMO should indicate that the user is on actual production environment, not on local prod one.

I'm not sure where is this used, but for practical purposes, I'm testing against prod servers/auth/etc. I think is a bit confusing to have it for "real" prod only. As I would like to test it locally before pushing it.

**Comment by ryelo** [comment]
`getEnv` should do the trick. if you're using prod.foo or c.r.c, you should get back prod.

**Comment by ryelo** [comment]
@josejulio Going to close this for now. If you would like additional functionality for something, just let me know and we can open up a Jira for tracking 😄
