### ISSUE TITLE
unknown app identifier: openshift

### ISSUE THREAD

**Issue by cben** [RedHatInsights/insights-chrome#1205]
Hello.  [OCM](https://cloud.redhat.com/openshift) does `insights.chrome.identifyApp('openshift');` and we're getting this error in JS console (not new, it's been there for a long time):
```
Uncaught (in promise) Error: unknown app identifier: openshift
    at Module.S (actions.js:33)
    at ReducerRegistry.js:1
    at entry.js:59
```

The relevant code is
https://github.com/RedHatInsights/insights-chrome/blob/688dca7d13e9a3d802221f65666fa8f1543189ac/src/js/redux/actions.js#L11-L30 

The data IIUC comes from https://github.com/RedHatInsights/cloud-services-config/blob/5458e71ba34177663a53f840954a2021a25e8336/main.yml#L545-L566 (?)
Looks like the code was supposed to match `group: openshift`, except it looks for `subItems` while the data has `sub_apps`??
Or am I confused?

**Comment by Hyperkid123** [comment]
@cben hello. Looking at the issues and I think we are dealing with parallelism issues.

When you go to the browser console and trigger the actian manullay via: `insights.chrome.identifyApp('openshift').then(console.log)` you don't get the error.

So the OCM UI must be triggering the action before the app's metadata was loaded. Usually, we advise gating the init call after the getUser promise finished or other application-specific initialization. But I believe that OCM allows un authed users as well? Can you point me towards the OCM UI triggers the action?

Note: in chrome 2 this won't be a problem because chrome will be always loaded and initialized before an app is rendered.

**Comment by cben** [comment]
Thanks. Closing, I haven't seen the error message for a long time, and now we're on chrome v2.
(We do still call `init()` and `identifyApp()` before `getUser` — https://gitlab.cee.redhat.com/service/uhc-portal/-/blob/master/src/chrome-main.jsx)
