### ISSUE TITLE
Left hand nav and main content scroll together

### ISSUE THREAD

**Issue by dlabrecq** [RedHatInsights/insights-chrome#201]
The left hand navigation pane, header, and main page content scroll together for Cost Management. I noticed other apps under Insights do not do this. Is this an Insights issue or something missed in Cost Management?

**To Reproduce**
1. Go to Cost Management
2. Go to AWS/OpenShift Details
3. Scroll down
4. See Left hand nav, page header, & main page content scroll together

*Expected behavior**
We should only be scrolling the app/table data.

**Screenshots**
![screenshot from 2019-02-24 23-53-57](https://user-images.githubusercontent.com/18352403/53307452-b5ea7b80-3890-11e9-9ecb-3707c30b6b88.png)

**Comment by ryelo** [comment]
@dlabrecq After debugging through some of your code, it looks like it's because you're slapping another `<main>` right after the main that chrome provides. After editing the DOM in the browser and moving all of your generated `main` into the one provides, everything scrolls correctly.

Screenshot of DOM
![Screen Shot 2019-03-27 at 12 05 48 PM](https://user-images.githubusercontent.com/12520842/55092313-c311aa80-5088-11e9-898b-4520454e9de5.png)

**Comment by ryelo** [comment]
@dlabrecq After digging around, the reason this is happening is because you're setting height variables in the root.

https://github.com/project-koku/koku-ui/blob/447e0b36e9bebf66fd7247992a1e1d2e2d74c58a/src/styles/global.css#L5

If you edit the DOM and remove the `#root { height: 100% }` it works on my end.

**Comment by ryelo** [comment]
@dlabrecq Is this still an issue or can this be closed?

**Comment by dlabrecq** [comment]
Yes, this can be closed. I appreciate your help!
