### ISSUE TITLE
Automation Platform link is broken

### ISSUE THREAD

**Issue by cbudz** [RedHatInsights/insights-chrome#726]
The documentation link to Automation Platform docs in `src/js/App/SideNav/index.js` is broken.

Correct link should be: https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/1.0/

**Comment by cbudz** [comment]
Added PR: https://github.com/RedHatInsights/insights-chrome/pull/727

**Comment by ryelo** [comment]
Reiterating our conversation from slack:

The link that is there is correct. When going to an external link, Adobe (required by RH) appends a tracker to the url: `/?extIdCarryOver=true&sc_cid=701f2000001Css0AAC`. Some pages don't like having that extra param, so we should talk to the access team to get that fixed.

We also leave off the `en-us` for localization and the `1.0` because it should default to the most recent version which allows us to keep up to date without extra PRs.
