### ISSUE TITLE
Multiple refresh attempts before data is displayed

### ISSUE THREAD

**Issue by dlabrecq** [RedHatInsights/insights-chrome#76]
The Insights team has provided a promise that we can wrap our API calls in to make sure we always have a token; however, this no longer seems to be working for the Koku UI. We still need to refresh the page in order to see data.

It appears that the token is requested after our providers API call.

Insights promise doc:
https://docs.google.com/document/d/1xjITNYbp1aw9Xu3lYLQppKQl-Rtj6_BaThwy1Zkazm4/edit#heading=h.8aucqk7x2oqb

Koku UI providers API call:
https://github.com/project-koku/koku-ui/blob/master/src/api/providers.ts#L76

Network requests:
![screen shot 2018-11-30 at 9 32 08 am](https://user-images.githubusercontent.com/17481322/49295087-d9b14780-f482-11e8-8014-23bd55778575.png)

**Comment by dlabrecq** [comment]
The Koku UI issue can be found here: https://github.com/project-koku/koku-ui/issues/250

**Comment by iphands** [comment]
@dlabrecq Perhaps the code is out of date where you are testing?

In prod (https://access.redhat.com/insights/platform/cost-management/) I dug through the sources available in my browser and noticed zero occurrences of  getUser in any downloaded JS.

It looks like the build job was not being picked up by the new Jenkins deployer for prod.
I think this was due to regular checks being done on known project branches, but no automated scan of the org happening.

I went ahead and triggered an org scan and will set up a recurring org scan.

Hope this is as simple as things were not up to date in prod.

**Comment by iphands** [comment]
Dug through a little on this on `master` so that we dont get sidetracked with the prod thing.
Looks like chrome is doing the right thing.

I changed providers.ts to do the following
```javascript
// See: http://koku-koku-dev.1b13.insights.openshiftapps.com/apidoc/index.html#api-Provider-GetProvider
export function getProviders() {
    const insights = (window as any).insights;

    function dbug() {
        const m = document.cookie.match(/rh_jwt=.*/);
        if (m.length > 0) {
            console.log('cookie found');
            console.log(m[0]);
        } else {
            console.log('no cookie');
        }
    }

    if (
        insights &&
            insights.chrome &&
            insights.chrome.auth &&
            insights.chrome.auth.getUser
    ) {
        return insights.chrome.auth.getUser()
            .then((t) => {
                dbug();
                console.log(t);
                return axios.get<Providers>(`providers/`);
            }).catch((e) => {
                dbug();
                console.log('catch');
                console.log(e);
            });
    } else {
        return axios.get<Providers>(`providers/`);
    }
}
```

And on the bad state (fresh session) I can see two calls to getProviders().
Both hit the "cookie found" case, both find/emit a valid rh_jwt in the document.cookie

The second one is odd. I see:
```
catch
providers.ts:42 Error: timeout of 4000ms exceeded
    at XMLHttpRequest.handleTimeout (xhr.js:95)
```

Also I see the same `(canceled)` request status. There are a few ways this can manifest in on the network console, but the most likely cause is something like the Dom element that started the network call was removed before things were completed. There are a few other cases in which that could happen too (switching src on an iframe mid load, actual networking issues, repeating a call that earlier got a 400 etc.).

**Comment by dlabrecq** [comment]
I'm curious why the token request is after providers?

I see the canceled providers request, but that's before the token request (per the screenshot above). Upon a refresh, it appears to work because the token has been refreshed.

Can you confirm the token you're obtaining from the cookie is valid?

**Comment by iphands** [comment]
> I'm curious why the token request is after providers?

Dunno I would like to see more of the networking console.
I see this:
![jnew](https://user-images.githubusercontent.com/129737/49451262-cc5eca80-f7ac-11e8-9dbd-b39f9ac0ec49.png)

> I see the canceled providers request, but that's before the token request (per the screenshot above). Upon a page refresh, it appears to work because the token has also been updated. That is, there is no cancel upon a second page refresh.
> 
> Can you confirm that the token you're obtaining from the cookie is valid and not something that was previously cached?

Yea, its a fresh browser session, zero cache. Also its the same token that validly works on refresh.

**Comment by iphands** [comment]
I would like to know exactly what you are doing instead of making a bunch of assumptions.
Can we setup some time to look over this together live?

**Comment by boaz1337** [comment]
After looking into it more with the help of @iphands the requests fail due to timeout.
In our axios configuration the request timeout is set to 4 seconds and it looks like it takes 7-10 seconds to receive the data from `cost-management/api/v1/providers` (at least on my machine).

Contacting with Alberto he figured out that there was a bug in the pubkey caching code. After few minutes he updated the system so the cache will be good for 1 hour, although there will be that bump that will take ~5.3 seconds (don't take my word for it) at the first time.

All in all, this is not related to insights-chrome and I believe we can close this ticket for now.
